### ISSUE TITLE
Implement `list`

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/valve-sql.clj#4]
See the notes here: https://github.com/ontodev/valve/blob/valve-sql-investigation/valve-function-investigation.org#list

We'll need a `WITH` clause.

**Comment by lmcmicu** [comment]
I have pushed two alternative implementations on two different branches.

* [The first](https://github.com/ontodev/valve-sql.clj/commit/351ce35366c179871154131e21ddef79ac13a1e8) is on the `main` branch and interprets `not(list(sep, expr))` as equivalent to `list(sep, not(expr))`.
* [The second](https://github.com/ontodev/valve-sql.clj/commit/4bfc75beb620ce275316b837246c13015a795fb9) is on the `alternate-not` branch and interprets `not(list(sep, expr))` as "verify that not all the tokens we get from splitting the target column by sep are instances of expr"

A similar decision will have to be made when it comes to the other functions (e.g., how do we interpret `not(split(...))`? I'll likewise push two alternative implementations to the `main` and `alternate-not` branches when the time comes.

**Comment by lmcmicu** [comment]
Closed either by https://github.com/ontodev/valve-sql.clj/commit/351ce35366c179871154131e21ddef79ac13a1e8 or https://github.com/ontodev/valve-sql.clj/commit/4bfc75beb620ce275316b837246c13015a795fb9

**Comment by jamesaoverton** [comment]
We'll go with the second option, which seems more correct to both of us.
